import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Auth
    'auth.welcome': 'Welcome to iHoogi',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Create Account',
    'auth.loginTooltip': 'Access your dashboard and questionnaires',
    'auth.registerTooltip': 'Create your account and build your first questionnaire',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.questionnaires': 'Questionnaires',
    'nav.responses': 'Responses',
    'nav.leads': 'Leads',
    'nav.affiliate': 'Affiliate',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.createNew': 'Create New Questionnaire',
    'dashboard.totalLeads': 'Total Leads',
    'dashboard.activeQuestionnaires': 'Active Questionnaires',
    'dashboard.responseRate': 'Response Rate',
    'dashboard.demoMode': 'Demo Mode',
    'dashboard.welcomeBack': 'Welcome back! Here\'s your business overview.',
    'dashboard.getStarted': 'Create your first questionnaire to get started.',
    'dashboard.recentQuestionnaires': 'Recent Questionnaires',
    'dashboard.recentQuestionnairesDesc': 'Your active questionnaires and their performance',
    'dashboard.noQuestionnaires': 'No questionnaires yet',
    'dashboard.noQuestionnairesDesc': 'Create your first questionnaire to start collecting leads and growing your business.',
    'dashboard.getStartedBtn': 'Get Started',
    
    // Questionnaires
    'questionnaires.title': 'Questionnaires',
    'questionnaires.subtitle': 'Create and manage your smart questionnaires',
    'questionnaires.new': 'New Questionnaire',
    'questionnaires.create': 'Create Your First Questionnaire',
    'questionnaires.getStarted': 'Get Started',
    'questionnaires.share': 'Share',
    'questionnaires.analytics': 'Analytics',
    'questionnaires.edit': 'Edit',
    'questionnaires.settings': 'Settings',
    'questionnaires.preview': 'Preview',
    'questionnaires.responses': 'Responses',
    'questionnaires.leads': 'Leads',
    'questionnaires.conversionRate': 'Conversion Rate',
    'questionnaires.active': 'active',
    'questionnaires.inactive': 'inactive',
    'questionnaires.draft': 'draft',
    'questionnaires.addQuestion': 'Add Question',
    'questionnaires.questionText': 'Question Text',
    'questionnaires.setDefaultAnswer': 'Set Default Answer',
    'questionnaires.defaultAnswer': 'Default Answer',
    'questionnaires.questionType': 'Question Type',
    'questionnaires.required': 'Required',
    'questionnaires.optional': 'Optional',
    
    // Question Types
    'questionTypes.text': 'Text',
    'questionTypes.textarea': 'Long Text',
    'questionTypes.select': 'Multiple Choice',
    'questionTypes.checkbox': 'Checkboxes',
    'questionTypes.radio': 'Radio Buttons',
    'questionTypes.email': 'Email',
    'questionTypes.phone': 'Phone',
    'questionTypes.number': 'Number',
    'questionTypes.date': 'Date',
    
    // Analytics 
    'analytics.title': 'Analytics',
    'analytics.conversionRate': 'Conversion Rate',
    
    // Leads
    'leads.title': 'Leads',
    'leads.subtitle': 'Manage and track your potential customers',
    'leads.name': 'Name',
    'leads.email': 'Email',
    'leads.phone': 'Phone',
    'leads.score': 'Score',
    'leads.source': 'Source',
    'leads.new': 'new',
    'leads.contacted': 'contacted',
    'leads.qualified': 'qualified',
    'leads.converted': 'converted',
    'leads.lost': 'lost',
    'leads.callNow': 'Call Now',
    'leads.sendFollowUp': 'Send Follow-up',
    'leads.followUpTemplate': 'Follow-up Message Template',
    'leads.sendMessage': 'Send Message',
    'leads.emailSubject': 'Email Subject',
    'leads.emailContent': 'Email Content',
    'leads.sendEmailAction': 'Send Email',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and questionnaire preferences',
    'settings.profile': 'Profile',
    'settings.branding': 'Branding',
    'settings.notifications': 'Notifications',
    'settings.language': 'Language',
    'settings.profileTitle': 'Profile Information',
    'settings.profileSubtitle': 'Update your personal and business information',
    'settings.brandingTitle': 'Questionnaire Branding',
    'settings.brandingSubtitle': 'Customize how your questionnaires look to clients',
    'settings.notificationsTitle': 'Notification Preferences',
    'settings.notificationsSubtitle': 'Choose how and when you want to be notified',
    'settings.languageTitle': 'Language & Regional Settings',
    'settings.languageSubtitle': 'Set your preferred language and regional preferences',
    'settings.fullName': 'Full Name',
    'settings.phone': 'Phone',
    'settings.company': 'Company',
    'settings.primaryColor': 'Primary Color',
    'settings.secondaryColor': 'Secondary Color',
    'settings.logoUrl': 'Logo URL',
    'settings.tagline': 'Business Tagline',
    'settings.preview': 'Preview',
    'settings.sampleQuestion': 'Sample Question',
    'settings.submit': 'Submit',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive email updates about new responses',
    'settings.leadAlerts': 'Lead Alerts',
    'settings.leadAlertsDesc': 'Get instant alerts for high-quality leads',
    'settings.weeklyReports': 'Weekly Reports',
    'settings.weeklyReportsDesc': 'Receive weekly performance summaries',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Enable browser push notifications',
    'settings.interfaceLanguage': 'Interface Language',
    'settings.interfaceLanguageDesc': 'Changes the language of the interface',
    'settings.languageInfo': 'Language Information',
    'settings.saveProfile': 'Save Profile',
    'settings.saveBranding': 'Save Branding',
    'settings.savePreferences': 'Save Preferences',
    'settings.uploadLogo': 'Upload logo from device',
    'settings.saveProfileTooltip': 'Save your profile changes',
    'settings.saveBrandingTooltip': 'Save your branding changes',
    'settings.savePreferencesTooltip': 'Save your notification preferences',
    
    // Hoogi Messages
    'hoogi.settingsMessage': 'Here you can customize your profile, branding, and notification preferences. Make sure your questionnaires reflect your brand perfectly!',
    'hoogi.welcomeMessage': 'Hi there! I\'m Hoogi, your friendly assistant. Let me help you create amazing questionnaires!',
    'hoogi.questionnairesDemo': 'Here are your active questionnaires! Each one is working 24/7 to collect leads for your business. Click \'Share\' to get the link, or \'Analytics\' to see performance.',
    'hoogi.questionnairesEmpty': 'Ready to create your first questionnaire? Click \'New Questionnaire\' to start collecting leads from your website visitors!',
    'hoogi.responsesDemo': 'Here are your latest questionnaire responses! I\'ve analyzed each one and provided sentiment analysis and lead quality scores. High-quality leads are great opportunities for follow-up!',
    'hoogi.responsesEmpty': 'Once you start receiving questionnaire responses, they\'ll appear here with AI-powered insights to help you prioritize your follow-ups.',
    'hoogi.leadsDemo': 'These are your qualified leads! I\'ve scored each one based on their responses. Use the action buttons to call, email, or send follow-up messages.',
    'hoogi.leadsEmpty': 'Your leads will appear here once people start submitting your questionnaires. I\'ll help you identify the best opportunities!',
    'hoogi.builderHelp': 'Build your questionnaire by adding questions one by one. You can edit, delete, or set default answers for each question. Don\'t forget to test it before sharing!',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    
    // Layout and navigation
    'layout.openMenu': 'Open navigation menu',
    
    // Sidebar
    'sidebar.toggleDemo': 'Toggle demo data visibility',
    'sidebar.navigateTo': 'Navigate to',
    'sidebar.helpMessage': 'Need help? Hoogi is here!',

    // Not Found
    'notFound.title': 'Page Not Found',
    'notFound.message': 'Sorry, the page you are looking for doesn\'t exist.',
    'notFound.backHome': 'Back to Home',

    // Affiliate Program
    'affiliate.title': 'Affiliate Program',
    'affiliate.subtitle': 'Earn money by referring new users to iHoogi',
    'affiliate.helpMessage': 'Earn $20 for every person who signs up using your referral link! Share iHoogi with your network and start earning today.',
    'affiliate.helpMessageDemo': 'Great work! You\'re earning money by sharing iHoogi with others. Keep sharing your referral link to boost your earnings!',
    'affiliate.referrals': 'Referrals',
    'affiliate.totalEarnings': 'Total Earnings',
    'affiliate.conversionRate': 'Conversion Rate',
    'affiliate.pendingPayment': 'Pending Payment',
    'affiliate.referralCodeTitle': 'Your Referral Code',
    'affiliate.referralCodeDesc': 'Share this code with your contacts',
    'affiliate.referralCode': 'Referral Code',
    'affiliate.referralLink': 'Referral Link',
    'affiliate.copyCode': 'Copy referral code',
    'affiliate.copyLink': 'Copy referral link',
    'affiliate.shareTitle': 'Share Your Link',
    'affiliate.shareDesc': 'Spread the word about iHoogi',
    'affiliate.shareWhatsApp': 'Share on WhatsApp',
    'affiliate.shareEmail': 'Share via Email',
    'affiliate.shareLinkedIn': 'Share on LinkedIn',
    'affiliate.howItWorksTitle': 'How the Affiliate Program Works',
    'affiliate.howItWorksDesc': 'Earn money by helping others discover iHoogi',
    'affiliate.step1Title': '1. Share Your Link',
    'affiliate.step1Desc': 'Share your unique referral link with friends, colleagues, and your network.',
    'affiliate.step2Title': '2. They Sign Up',
    'affiliate.step2Desc': 'When someone uses your link to register and subscribes to a paid plan.',
    'affiliate.step3Title': '3. You Earn Money',
    'affiliate.step3Desc': 'Receive $20 commission for each successful referral. Payments are made monthly.',
    'affiliate.copySuccess': 'Copied!',
    'affiliate.copyCodeSuccess': 'Referral code copied to clipboard.',
    'affiliate.copyLinkSuccess': 'Referral link copied to clipboard.',
    'affiliate.shareMessage': 'Check out iHoogi - the smart questionnaire tool that converts visitors into leads!',
    
    // Tooltips
    'tooltip.createQuestionnaire': 'Create a new questionnaire',
    'tooltip.shareQuestionnaire': 'Share this questionnaire',
    'tooltip.analytics': 'View detailed analytics',
    'tooltip.editQuestionnaire': 'Edit questionnaire',
    'tooltip.questionnaireSettings': 'Questionnaire settings',
    'tooltip.preview': 'View live questionnaire',
    'tooltip.reply': 'Reply to this response',
    'tooltip.schedule': 'Schedule follow-up',
    'tooltip.analysis': 'View detailed analysis',
    'tooltip.email': 'Send email',
    'tooltip.call': 'Call client',
    'tooltip.callLead': 'Call this lead',
    'tooltip.emailLead': 'Send email to lead',
    'tooltip.followUp': 'Send follow-up message',
    'tooltip.addQuestion': 'Add a new question',
    'tooltip.editQuestion': 'Edit this question',
    'tooltip.deleteQuestion': 'Delete this question',
    'tooltip.setDefault': 'Set default answer',
    'tooltip.duplicate': 'Duplicate this questionnaire',
    'tooltip.aiSuggest': 'Get AI suggestions for answer',
    'tooltip.quickAdd': 'Add quick question',
    'tooltip.mobilePreview': 'Preview on mobile',
    'tooltip.desktopPreview': 'Preview on desktop',
    'tooltip.dragQuestion': 'Drag to reorder',
    'tooltip.shareLink': 'Get shareable link',
    'tooltip.autosave': 'Changes auto-saved',
    'tooltip.setQuestionnaireLanguage': 'Set questionnaire language',
    'tooltip.markRequired': 'Mark as required',
    'tooltip.brandingDefaults': 'Save as default branding',
    'tooltip.readyToSend': 'Ready to share with clients',
    
    // Toast Messages  
    'toast.profileUpdated': 'Profile updated!',
    'toast.profileUpdatedDesc': 'Your profile information has been saved.',
    'toast.brandingUpdated': 'Branding updated!',
    'toast.brandingUpdatedDesc': 'Your questionnaire branding has been saved.',
    'toast.notificationsUpdated': 'Notification preferences updated!',
    'toast.notificationsUpdatedDesc': 'Your notification settings have been saved.',
    'toast.linkCopied': 'Link copied!',
    'toast.linkCopiedDesc': 'Shareable link has been copied to clipboard.',
    'toast.emailSent': 'Email sent!',
    'toast.emailSentDesc': 'Your email has been sent successfully.',
    'toast.messageSent': 'Message sent!',
    'toast.messageSentDesc': 'Your follow-up message has been sent.',
    'toast.questionAdded': 'Question added!',
    'toast.questionAddedDesc': 'New question has been added to your questionnaire.',
    'toast.questionUpdated': 'Question updated!',
    'toast.questionUpdatedDesc': 'Question has been updated successfully.',
    'toast.questionDeleted': 'Question deleted!',
    'toast.questionDeletedDesc': 'Question has been removed from your questionnaire.',
    'toast.defaultAnswerSet': 'Default answer set!',
    'toast.defaultAnswerSetDesc': 'Default answer has been saved for this question.',
    'toast.questionnaireDuplicated': 'Questionnaire duplicated!',
    'toast.questionnaireDuplicatedDesc': 'A copy has been created successfully.',
    'toast.autosaved': 'Auto-saved!',
    'toast.autosavedDesc': 'Your changes have been automatically saved.',
    'toast.aiSuggestionGenerated': 'AI suggestion generated!',
    'toast.aiSuggestionGeneratedDesc': 'Smart answer suggestion is ready.',
    'toast.questionReordered': 'Questions reordered!',
    'toast.questionReorderedDesc': 'Question order has been updated.',
    'toast.brandingDefaultsSaved': 'Branding defaults saved!',
    'toast.brandingDefaultsSavedDesc': 'These settings will be used for new questionnaires.',
    
    // Auth Additional Messages
    'toast.loginSuccess': 'Welcome back!',
    'toast.loginSuccessDesc': 'You\'ve been successfully logged in.',
    
    // Onboarding
    'onboarding.title': 'Create Your First Questionnaire',
    'onboarding.businessInfo': 'Business Information',
    'onboarding.businessInfoDesc': 'Tell us about your business',
    'onboarding.questionnaireSetup': 'Questionnaire Setup',
    'onboarding.questionnaireSetupDesc': 'Create questions for your clients',
    'onboarding.customization': 'Customization',
    'onboarding.customizationDesc': 'Make it yours with branding',
    'onboarding.businessCategory': 'Business Category',
    'onboarding.selectProfession': 'Select your profession',
    'onboarding.companyName': 'Company Name',
    'onboarding.companyNamePlaceholder': 'Your Company Name',
    'onboarding.suggestedQuestions': 'I can suggest questions based on your profession',
    'onboarding.loadSuggested': 'Load Suggested Questions',
    'onboarding.enterQuestion': 'Enter your question...',
    'onboarding.logoUrl': 'Company Logo URL (Optional)',
    'onboarding.logoPlaceholder': 'https://example.com/logo.png',
    'onboarding.preview': 'Preview',
    'onboarding.thankYou': 'Thank you for your interest! Please answer a few questions to help us serve you better.',
    'onboarding.sampleQuestion': 'Sample question',
    'onboarding.clientAnswer': 'Client\'s answer...',
    'onboarding.previous': 'Previous',
    'onboarding.next': 'Next',
    'onboarding.createQuestionnaire': 'Create Questionnaire',
    'onboarding.questionsLoaded': 'Questions Loaded',
    'onboarding.questionnaireCreated': 'Questionnaire Created!',
    'onboarding.questionnaireCreatedDesc': 'Your questionnaire has been created successfully.',
    'onboarding.step1Help': 'Let\'s start by learning about your business. This helps me suggest the perfect questions for your clients.',
    'onboarding.step2Help': 'Great! Now let\'s create questions that will help you understand your potential clients better.',
    'onboarding.step3Help': 'Almost done! Let\'s add some personal touches to make your questionnaire uniquely yours.',
    
    // Business Categories
    'category.lawyer': 'Legal Services',
    'category.coach': 'Life Coach',
    'category.insurance': 'Insurance Agent',
    'category.consultant': 'Business Consultant',
    'category.therapist': 'Therapist',
    'category.accountant': 'Accountant',
    'category.other': 'Other',

    // Questionnaire Builder Advanced
    'builder.title': 'Create Questionnaire',
    'builder.subtitle': 'Build smart questionnaires to convert visitors into leads',
    'builder.selectCategory': 'Select Category',
    'builder.selectCategoryDesc': 'Choose your business category for AI suggestions',
    'builder.suggestedQuestions': 'Suggested Questions',
    'builder.quickQuestions': 'Quick Add Questions',
    'builder.customQuestions': 'Custom Questions', 
    'builder.preview': 'Preview',
    'builder.mobilePreview': 'Mobile Preview',
    'builder.desktopPreview': 'Desktop Preview',
    'builder.questionnaireLanguage': 'Questionnaire Language',
    'builder.questionnaireLanguageDesc': 'Language for questions and answers',
    'builder.branding': 'Branding & Design',
    'builder.automation': 'Automation Settings',
    'builder.readyToSend': 'Ready to Send!',
    'builder.share': 'Share Questionnaire',
    'builder.aiSuggestAnswer': 'AI Suggest Answer',
    'builder.addQuickQuestion': 'Add Quick Question',
    'builder.duplicateQuestionnaire': 'Duplicate Questionnaire',
    'builder.saveAsDraft': 'Save as Draft',
    'builder.autosave': 'Auto-save',
    'builder.autosaveEnabled': 'Auto-save enabled',
    'builder.lastSaved': 'Last saved',
    'builder.unsavedChanges': 'Unsaved changes',
    'builder.dragToReorder': 'Drag to reorder questions',
    'builder.questionOrder': 'Question Order',
    'builder.editInPreview': 'Edit in Preview',
    'builder.shareOptions': 'Share Options',
    'builder.getLink': 'Get Link',
    'builder.shareWhatsApp': 'Share on WhatsApp',
    'builder.shareEmail': 'Share via Email',
    'builder.shareSMS': 'Send via SMS',
    'builder.previewMessage': 'Preview Message',
    'builder.recipientView': 'Recipient will see',
    'builder.brandingDefaults': 'Save as Default Branding',
    'builder.useDefaults': 'Use Default Branding',
    'builder.questionSettings': 'Question Settings',
    'builder.answerType': 'Answer Type',
    'builder.validation': 'Validation',
    'builder.logic': 'Question Logic',
    'builder.skipLogic': 'Skip Logic',
    'builder.conditionalLogic': 'Conditional Logic',
    'builder.requiredField': 'Required Field',
    'builder.optionalField': 'Optional Field',
    'builder.helpText': 'Help Text',
    'builder.placeholder': 'Placeholder Text',
    'builder.characterLimit': 'Character Limit',
    'builder.minLength': 'Minimum Length',
    'builder.maxLength': 'Maximum Length',
    'builder.emailValidation': 'Email Validation',
    'builder.phoneValidation': 'Phone Validation',
    'builder.urlValidation': 'URL Validation',
    'builder.numberValidation': 'Number Validation',
    'builder.dateValidation': 'Date Validation',
    
    // Responses 
    'responses.filterResponses': 'Filter Responses',
    'responses.searchPlaceholder': 'Search by name or email...',
    'responses.recent': 'Recent Responses',
    'responses.recentDesc': 'Click on any response to view details and reply',
    'responses.filterByStatus': 'Filter by status',
    'responses.allResponses': 'All Responses',
    'responses.client': 'Client',
    'responses.questionnaire': 'Questionnaire',
    'responses.sentiment': 'Sentiment',
    'responses.leadQuality': 'Lead Quality',
    'responses.status': 'Status',
    'responses.date': 'Date',
    'responses.actions': 'Actions',
    'responses.positive': 'positive',
    'responses.neutral': 'neutral',
    'responses.negative': 'negative',
    'responses.replied': 'Replied',
    'responses.pending': 'Pending',
    'responses.scheduled': 'Scheduled',
    'responses.noResponses': 'No responses yet',
    'responses.noResponsesDesc': 'Once people start filling out your questionnaires, their responses will appear here.',
    'responses.shareQuestionnaires': 'Share Your Questionnaires',
  },
  he: {
    // Auth
    'auth.welcome': 'ברוכים הבאים ל-iHoogi',
    'auth.login': 'התחברות',
    'auth.register': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.confirmPassword': 'אימות סיסמה',
    'auth.loginButton': 'התחבר',
    'auth.registerButton': 'צור חשבון',
    'auth.loginTooltip': 'גישה ללוח הבקרה והשאלונים שלך',
    'auth.registerTooltip': 'צור חשבון ובנה את השאלון הראשון שלך',
    
    // Navigation
    'nav.dashboard': 'לוח בקרה',
    'nav.questionnaires': 'שאלונים',
    'nav.responses': 'תגובות',
    'nav.leads': 'לידים',
    'nav.affiliate': 'שותפים',
    'nav.settings': 'הגדרות',
    
    // Dashboard
    'dashboard.title': 'לוח בקרה',
    'dashboard.createNew': 'צור שאלון חדש',
    'dashboard.totalLeads': 'סה"כ לידים',
    'dashboard.activeQuestionnaires': 'שאלונים פעילים',
    'dashboard.responseRate': 'אחוז תגובה',
    'dashboard.demoMode': 'מצב הדגמה',
    'dashboard.welcomeBack': 'ברוכים השבים! הנה סקירת העסק שלכם.',
    'dashboard.getStarted': 'צרו את השאלון הראשון שלכם כדי להתחיל.',
    'dashboard.recentQuestionnaires': 'שאלונים אחרונים',
    'dashboard.recentQuestionnairesDesc': 'השאלונים הפעילים שלכם והביצועים שלהם',
    'dashboard.noQuestionnaires': 'אין עדיין שאלונים',
    'dashboard.noQuestionnairesDesc': 'צרו את השאלון הראשון שלכם כדי להתחיל לאסוף לידים ולהגדיל את העסק שלכם.',
    'dashboard.getStartedBtn': 'התחילו',
    
    // Questionnaires
    'questionnaires.title': 'שאלונים',
    'questionnaires.subtitle': 'צור ונהל את השאלונים החכמים שלך',
    'questionnaires.new': 'שאלון חדש',
    'questionnaires.create': 'צור את השאלון הראשון שלך',
    'questionnaires.getStarted': 'התחל כעת',
    'questionnaires.share': 'שיתוף',
    'questionnaires.analytics': 'ניתוחים',
    'questionnaires.edit': 'עריכה',
    'questionnaires.settings': 'הגדרות',
    'questionnaires.preview': 'תצוגה מקדימה',
    'questionnaires.responses': 'תגובות',
    'questionnaires.leads': 'לידים',
    'questionnaires.conversionRate': 'שיעור המרה',
    'questionnaires.active': 'פעיל',
    'questionnaires.inactive': 'לא פעיל',
    'questionnaires.draft': 'טיוטה',
    'questionnaires.addQuestion': 'הוסף שאלה',
    'questionnaires.questionText': 'טקסט השאלה',
    'questionnaires.setDefaultAnswer': 'הגדר תשובה קבועה',
    'questionnaires.defaultAnswer': 'תשובה קבועה',
    'questionnaires.questionType': 'סוג השאלה',
    'questionnaires.required': 'חובה',
    'questionnaires.optional': 'רשות',
    
    // Question Types
    'questionTypes.text': 'טקסט',
    'questionTypes.textarea': 'טקסט ארוך',
    'questionTypes.select': 'בחירה מרובה',
    'questionTypes.checkbox': 'תיבות סימון',
    'questionTypes.radio': 'כפתורי בחירה',
    'questionTypes.email': 'אימייל',
    'questionTypes.phone': 'טלפון',
    'questionTypes.number': 'מספר',
    'questionTypes.date': 'תאריך',
    
    // Responses & Leads
    'responses.title': 'תגובות',
    'responses.subtitle': 'נהל והגב לשליחות השאלונים',
    'responses.filterBy': 'סינון לפי סטטוס',
    'responses.searchPlaceholder': 'חיפוש לפי שם או אימייל...',
    'responses.client': 'לקוח',
    'responses.questionnaire': 'שאלון',
    'responses.sentiment': 'סנטימנט',
    'responses.leadQuality': 'איכות הליד',
    'responses.status': 'סטטוס',
    'responses.date': 'תאריך',
    'responses.actions': 'פעולות',
    'responses.reply': 'הגב',
    'responses.schedule': 'תזמן',
    'responses.viewAnalysis': 'הצג ניתוח',
    'responses.sendEmail': 'שלח מייל',
    'responses.call': 'התקשר',
    'responses.pending': 'ממתין',
    'responses.replied': 'נענה',
    'responses.scheduled': 'מתוזמן',
    'responses.positive': 'חיובי',
    'responses.neutral': 'נייטרלי',
    'responses.negative': 'שלילי',
    'responses.high': 'גבוהה',
    'responses.medium': 'בינונית',
    'responses.low': 'נמוכה',
    
    // Leads
    'leads.title': 'לידים',
    'leads.subtitle': 'נהל ועקוב אחר הלקוחות הפוטנציאליים שלך',
    'leads.name': 'שם',
    'leads.email': 'אימייל',
    'leads.phone': 'טלפון',
    'leads.score': 'ציון',
    'leads.source': 'מקור',
    'leads.new': 'חדש',
    'leads.contacted': 'נוצר קשר',
    'leads.qualified': 'מוכשר',
    'leads.converted': 'הומר',
    'leads.lost': 'אבוד',
    'leads.callNow': 'התקשר כעת',
    'leads.sendFollowUp': 'שלח מעקב',
    'leads.followUpTemplate': 'תבנית הודעת מעקב',
    'leads.sendMessage': 'שלח הודעה',
    'leads.emailSubject': 'נושא המייל',
    'leads.emailContent': 'תוכן המייל',
    'leads.sendEmailAction': 'שלח מייל',
    
    // Settings
    'settings.title': 'הגדרות',
    'settings.subtitle': 'נהל את החשבון והעדפות השאלונים שלך',
    'settings.profile': 'פרופיל',
    'settings.branding': 'מיתוג',
    'settings.notifications': 'התראות',
    'settings.language': 'שפה',
    'settings.profileTitle': 'מידע אישי',
    'settings.profileSubtitle': 'עדכן את המידע האישי והעסקי שלך',
    'settings.brandingTitle': 'מיתוג השאלונים',
    'settings.brandingSubtitle': 'התאם אישית איך השאלונים שלך נראים ללקוחות',
    'settings.notificationsTitle': 'העדפות התראות',
    'settings.notificationsSubtitle': 'בחר איך ומתי תרצה לקבל התראות',
    'settings.languageTitle': 'הגדרות שפה ואזור',
    'settings.languageSubtitle': 'קבע את השפה המועדפת וההעדפות האזוריות שלך',
    'settings.fullName': 'שם מלא',
    'settings.phone': 'טלפון',
    'settings.company': 'חברה',
    'settings.primaryColor': 'צבע ראשי',
    'settings.secondaryColor': 'צבע משני',
    'settings.logoUrl': 'כתובת לוגו',
    'settings.tagline': 'סלוגן עסקי',
    'settings.preview': 'תצוגה מקדימה',
    'settings.sampleQuestion': 'שאלה לדוגמה',
    'settings.submit': 'שלח',
    'settings.emailNotifications': 'התראות אימייל',
    'settings.emailNotificationsDesc': 'קבל עדכוני אימייל על תשובות חדשות',
    'settings.leadAlerts': 'התראות לידים',
    'settings.leadAlertsDesc': 'קבל התראות מיידיות על לידים איכותיים',
    'settings.weeklyReports': 'דוחות שבועיים',
    'settings.weeklyReportsDesc': 'קבל סיכומי ביצועים שבועיים',
    'settings.pushNotifications': 'התראות דחיפה',
    'settings.pushNotificationsDesc': 'הפעל התראות דחיפה בדפדפן',
    'settings.interfaceLanguage': 'שפת הממשק',
    'settings.interfaceLanguageDesc': 'משנה את שפת הממשק',
    'settings.languageInfo': 'מידע על השפה',
    'settings.saveProfile': 'שמור פרופיל',
    'settings.saveBranding': 'שמור מיתוג',
    'settings.savePreferences': 'שמור העדפות',
    'settings.uploadLogo': 'העלה לוגו מהמכשיר',
    'settings.saveProfileTooltip': 'שמור את השינויים בפרופיל שלך',
    'settings.saveBrandingTooltip': 'שמור את שינויי המיתוג שלך',
    'settings.savePreferencesTooltip': 'שמור את העדפות ההתראות שלך',
    
    // Hoogi Messages
    'hoogi.settingsMessage': 'כאן תוכל להתאים אישית את הפרופיל, המיתוג והעדפות ההתראות שלך. וודא שהשאלונים שלך משקפים את המותג שלך בצורה מושלמת!',
    'hoogi.welcomeMessage': 'שלום! אני הוגי, העוזר הידידותי שלך. בוא אעזור לך ליצור שאלונים מדהימים!',
    'hoogi.questionnairesDemo': 'הנה השאלונים הפעילים שלך! כל אחד עובד 24/7 לאיסוף לידים לעסק שלך. לחץ על \'שיתוף\' לקבלת הקישור, או \'ניתוחים\' לראות ביצועים.',
    'hoogi.questionnairesEmpty': 'מוכן ליצור את השאלון הראשון שלך? לחץ על \'שאלון חדש\' כדי להתחיל לאסוף לידים מאורחי האתר שלך!',
    'hoogi.responsesDemo': 'הנה התגובות האחרונות לשאלונים שלך! ניתחתי כל אחת וסיפקתי ניתוח סנטימנט וציוני איכות ליד. לידים באיכות גבוהה הם הזדמנויות מעולות למעקב!',
    'hoogi.responsesEmpty': 'ברגע שתתחיל לקבל תגובות לשאלונים, הן יופיעו כאן עם תובנות מבוססות AI שיעזרו לך לתעדף את המעקבים שלך.',
    'hoogi.leadsDemo': 'אלה הלידים המוכשרים שלך! דירגתי כל אחד מהם על סמך התגובות שלהם. השתמש בכפתורי הפעולה כדי להתקשר, לשלוח מייל או הודעות מעקב.',
    'hoogi.leadsEmpty': 'הלידים שלך יופיעו כאן ברגע שאנשים יתחילו לשלוח את השאלונים שלך. אני אעזור לך לזהות את ההזדמנויות הטובות ביותר!',
    'hoogi.builderHelp': 'בנה את השאלון שלך על ידי הוספת שאלות אחת אחת. תוכל לערוך, למחוק או להגדיר תשובות ברירת מחדל לכל שאלה. אל תשכח לבדוק אותו לפני השיתוף!',
    'hoogi.dashboardDemo': 'כל הכבוד! השאלונים שלכם מייצרים לידים איכותיים. בדקו את התגובות האחרונות שלכם ועקבו אחר לקוחות בעלי פוטנציאל גבוה.',
    'hoogi.dashboardEmpty': 'ברוכים הבאים ל-iHoogi! אני מתרגש לעזור לכם ליצור את השאלון החכם הראשון שלכם. לחצו על "צור שאלון חדש" כדי להתחיל!',
    
    // Common
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.edit': 'עריכה',
    'common.delete': 'מחיקה',
    'common.share': 'שיתוף',
    'common.copy': 'העתק',
    'common.copied': 'הועתק!',
    'common.close': 'סגור',
    'common.open': 'פתח',
    'common.loading': 'טוען...',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.warning': 'אזהרה',
    'common.info': 'מידע',
    'common.confirm': 'אישור',
    'common.yes': 'כן',
    'common.no': 'לא',
    'common.add': 'הוסף',
    'common.remove': 'הסר',
    'common.update': 'עדכן',
    'common.create': 'צור',
    'common.search': 'חיפוש',
    'common.filter': 'סינון',
    'common.all': 'הכל',
    'common.none': 'ללא',
    'common.select': 'בחר',
    'common.submit': 'שלח',
    'common.reset': 'איפוס',
    'common.back': 'חזור',
    'common.next': 'הבא',
    'common.previous': 'הקודם',
    'common.continue': 'המשך',
    
    // Layout and navigation
    'layout.openMenu': 'פתח תפריט ניווט',
    
    // Sidebar
    'sidebar.toggleDemo': 'החלף תצוגת נתוני דמו',
    'sidebar.navigateTo': 'נווט ל',
    'sidebar.helpMessage': 'צריך עזרה? הוגי כאן!',

    // Not Found
    'notFound.title': 'הדף לא נמצא',
    'notFound.message': 'מצטערים, הדף שאתה מחפש לא קיים.',
    'notFound.backHome': 'חזרה לעמוד הבית',

    // Affiliate Program
    'affiliate.title': 'תוכנית שותפים',
    'affiliate.subtitle': 'הרווח כסף על ידי הפניית משתמשים חדשים ל-iHoogi',
    'affiliate.helpMessage': 'הרווח 20$ עבור כל אדם שנרשם באמצעות קישור ההפניה שלך! שתף את iHoogi עם הרשת שלך והתחל להרווח היום.',
    'affiliate.helpMessageDemo': 'עבודה מעולה! אתה מרווח כסף על ידי שיתוף iHoogi עם אחרים. המשך לשתף את קישור ההפניה שלך כדי להגדיל את הרווחים!',
    'affiliate.referrals': 'הפניות',
    'affiliate.totalEarnings': 'סך הרווחים',
    'affiliate.conversionRate': 'שיעור המרה',
    'affiliate.pendingPayment': 'תשלום ממתין',
    'affiliate.referralCodeTitle': 'קוד ההפניה שלך',
    'affiliate.referralCodeDesc': 'שתף את הקוד הזה עם הקשרים שלך',
    'affiliate.referralCode': 'קוד הפניה',
    'affiliate.referralLink': 'קישור הפניה',
    'affiliate.copyCode': 'העתק קוד הפניה',
    'affiliate.copyLink': 'העתק קישור הפניה',
    'affiliate.shareTitle': 'שתף את הקישור שלך',
    'affiliate.shareDesc': 'הפץ את הבשורה על iHoogi',
    'affiliate.shareWhatsApp': 'שתף בווטסאפ',
    'affiliate.shareEmail': 'שתף במייל',
    'affiliate.shareLinkedIn': 'שתף בלינקדאין',
    'affiliate.howItWorksTitle': 'איך תוכנית השותפים עובדת',
    'affiliate.howItWorksDesc': 'הרווח כסף על ידי עזרה לאחרים לגלות את iHoogi',
    'affiliate.step1Title': '1. שתף את הקישור שלך',
    'affiliate.step1Desc': 'שתף את קישור ההפניה הייחודי שלך עם חברים, עמיתים והרשת שלך.',
    'affiliate.step2Title': '2. הם נרשמים',
    'affiliate.step2Desc': 'כאשר מישהו משתמש בקישור שלך כדי להירשם ולהירשם לתכנית בתשלום.',
    'affiliate.step3Title': '3. אתה מרווח כסף',
    'affiliate.step3Desc': 'קבל עמלה של 20$ עבור כל הפניה מוצלחת. התשלומים מתבצעים מדי חודש.',
    'affiliate.copySuccess': 'הועתק!',
    'affiliate.copyCodeSuccess': 'קוד ההפניה הועתק ללוח.',
    'affiliate.copyLinkSuccess': 'קישור ההפניה הועתק ללוח.',
    'affiliate.shareMessage': 'בדוק את iHoogi - הכלי החכם לשאלונים שהופך מבקרים ללידים!',
    
    // Settings additional
    'settings.logoPlaceholder': 'https://example.com/logo.png',
    'settings.taglinePlaceholder': 'תיאור קצר של העסק שלך...',
    'settings.sampleAnswerPlaceholder': 'תשובת הלקוח...',
    
    // Tooltips
    'tooltip.createQuestionnaire': 'צור שאלון חדש',
    'tooltip.shareQuestionnaire': 'שתף את השאלון הזה',
    'tooltip.analytics': 'הצג ניתוחים מפורטים',
    'tooltip.editQuestionnaire': 'ערוך שאלון',
    'tooltip.questionnaireSettings': 'הגדרות שאלון',
    'tooltip.preview': 'הצג שאלון חי',
    'tooltip.reply': 'הגב לתגובה זו',
    'tooltip.schedule': 'תזמן מעקב',
    'tooltip.analysis': 'הצג ניתוח מפורט',
    'tooltip.email': 'שלח מייל',
    'tooltip.call': 'התקשר ללקוח',
    'tooltip.callLead': 'התקשר לליד זה',
    'tooltip.emailLead': 'שלח מייל לליד',
    'tooltip.followUp': 'שלח הודעת מעקב',
    'tooltip.addQuestion': 'הוסף שאלה חדשה',
    'tooltip.editQuestion': 'ערוך את השאלה הזו',
    'tooltip.deleteQuestion': 'מחק את השאלה הזו',
    'tooltip.setDefault': 'הגדר תשובת ברירת מחדל',
    'tooltip.viewAnalytics': 'צפה בניתוח מפורט של',
    'tooltip.viewQuestionnaire': 'לחץ לצפייה בפרטי השאלון',
    
    // Toast Messages
    'toast.profileUpdated': 'הפרופיל עודכן!',
    'toast.profileUpdatedDesc': 'המידע האישי שלך נשמר.',
    'toast.brandingUpdated': 'המיתוג עודכן!',
    'toast.brandingUpdatedDesc': 'מיתוג השאלונים שלך נשמר.',
    'toast.notificationsUpdated': 'העדפות ההתראות עודכנו!',
    'toast.notificationsUpdatedDesc': 'הגדרות ההתראות שלך נשמרו.',
    'toast.linkCopied': 'הקישור הועתק!',
    'toast.linkCopiedDesc': 'קישור השיתוף הועתק ללוח העריכה.',
    'toast.emailSent': 'המייל נשלח!',
    'toast.emailSentDesc': 'המייל שלך נשלח בהצלחה.',
    'toast.messageSent': 'ההודעה נשלחה!',
    'toast.messageSentDesc': 'הודעת המעקב שלך נשלחה.',
    'toast.questionAdded': 'השאלה נוספה!',
    'toast.questionAddedDesc': 'שאלה חדשה נוספה לשאלון שלך.',
    'toast.questionUpdated': 'השאלה עודכנה!',
    'toast.questionUpdatedDesc': 'השאלה עודכנה בהצלחה.',
    'toast.questionDeleted': 'השאלה נמחקה!',
    'toast.questionDeletedDesc': 'השאלה הוסרה מהשאלון שלך.',
    'toast.defaultAnswerSet': 'תשובת ברירת מחדל נקבעה!',
    'toast.defaultAnswerSetDesc': 'תשובת ברירת המחדל נשמרה לשאלה זו.',
    'toast.questionnaireDuplicated': 'השאלון שוכפל!',
    'toast.questionnaireDuplicatedDesc': 'עותק נוצר בהצלחה.',
    'toast.autosaved': 'נשמר אוטומטית!',
    'toast.autosavedDesc': 'השינויים שלך נשמרו אוטומטית.',
    'toast.aiSuggestionGenerated': 'הצעת AI נוצרה!',
    'toast.aiSuggestionGeneratedDesc': 'הצעת תשובה חכמה מוכנה.',
    'toast.questionReordered': 'סדר השאלות שונה!',
    'toast.questionReorderedDesc': 'סדר השאלות עודכן.',
    'toast.brandingDefaultsSaved': 'ברירות מחדל למיתוג נשמרו!',
    'toast.brandingDefaultsSavedDesc': 'הגדרות אלה ישמשו לשאלונים חדשים.',

    // Tooltips Hebrew
    'tooltip.duplicate': 'שכפל את השאלון הזה',
    'tooltip.aiSuggest': 'קבל הצעות AI לתשובה',
    'tooltip.quickAdd': 'הוסף שאלה מהירה',
    'tooltip.mobilePreview': 'תצוגה מקדימה במובייל',
    'tooltip.desktopPreview': 'תצוגה מקדימה בדסקטופ',
    'tooltip.dragQuestion': 'גרור לשינוי סדר',
    'tooltip.shareLink': 'קבל קישור לשיתוף',
    'tooltip.autosave': 'שינויים נשמרו אוטומטית',
    'tooltip.setQuestionnaireLanguage': 'הגדר שפת השאלון',
    'tooltip.markRequired': 'סמן כחובה',
    'tooltip.brandingDefaults': 'שמור כמיתוג ברירת מחדל',
    'tooltip.readyToSend': 'מוכן לשיתוף עם לקוחות',

    // Auth Additional Messages Hebrew
    'toast.loginSuccess': 'ברוך הבא!',
    'toast.loginSuccessDesc': 'התחברת בהצלחה.',

    // Onboarding Hebrew
    'onboarding.title': 'צור את השאלון הראשון שלך',
    'onboarding.businessInfo': 'מידע עסקי',
    'onboarding.businessInfoDesc': 'ספר לנו על העסק שלך',
    'onboarding.questionnaireSetup': 'הגדרת שאלון',
    'onboarding.questionnaireSetupDesc': 'צור שאלות עבור הלקוחות שלך',
    'onboarding.customization': 'התאמה אישית',
    'onboarding.customizationDesc': 'הפוך אותו שלך עם מיתוג',
    'onboarding.businessCategory': 'קטגוריית עסק',
    'onboarding.selectProfession': 'בחר את המקצוע שלך',
    'onboarding.companyName': 'שם החברה',
    'onboarding.companyNamePlaceholder': 'שם החברה שלך',
    'onboarding.suggestedQuestions': 'אני יכול להציע שאלות על בסיס המקצוע שלך',
    'onboarding.loadSuggested': 'טען שאלות מוצעות',
    'onboarding.enterQuestion': 'הזן את השאלה שלך...',
    'onboarding.logoUrl': 'כתובת לוגו החברה (אופציונלי)',
    'onboarding.logoPlaceholder': 'https://example.com/logo.png',
    'onboarding.preview': 'תצוגה מקדימה',
    'onboarding.thankYou': 'תודה על העניין שלך! אנא ענה על מספר שאלות כדי לעזור לנו לשרת אותך טוב יותר.',
    'onboarding.sampleQuestion': 'שאלה לדוגמה',
    'onboarding.clientAnswer': 'תשובת הלקוח...',
    'onboarding.previous': 'הקודם',
    'onboarding.next': 'הבא',
    'onboarding.createQuestionnaire': 'צור שאלון',
    'onboarding.questionsLoaded': 'שאלות נטענו',
    'onboarding.questionnaireCreated': 'השאלון נוצר!',
    'onboarding.questionnaireCreatedDesc': 'השאלון שלך נוצר בהצלחה.',
    'onboarding.step1Help': 'בוא נתחיל בלימוד על העסק שלך. זה עוזר לי להציע את השאלות המושלמות עבור הלקוחות שלך.',
    'onboarding.step2Help': 'מעולה! עכשיו בוא ניצור שאלות שיעזרו לך להבין טוב יותר את הלקוחות הפוטנציאליים שלך.',
    'onboarding.step3Help': 'כמעט סיימנו! בוא נוסיף כמה נגיעות אישיות כדי להפוך את השאלון שלך לייחודי.',

    // Business Categories Hebrew
    'category.lawyer': 'שירותים משפטיים',
    'category.coach': 'מאמן חיים',
    'category.insurance': 'סוכן ביטוח',
    'category.consultant': 'יועץ עסקי',
    'category.therapist': 'מטפל',
    'category.accountant': 'רואה חשבון',
    'category.other': 'אחר',

    // Questionnaire Builder Advanced Hebrew
    'builder.title': 'צור שאלון',
    'builder.subtitle': 'בנה שאלונים חכמים להמרת מבקרים ללידים',
    'builder.selectCategory': 'בחר קטגוריה',
    'builder.selectCategoryDesc': 'בחר את קטגוריית העסק שלך להצעות AI',
    'builder.suggestedQuestions': 'שאלות מוצעות',
    'builder.quickQuestions': 'הוספה מהירה של שאלות',
    'builder.customQuestions': 'שאלות מותאמות אישית',
    'builder.preview': 'תצוגה מקדימה',
    'builder.mobilePreview': 'תצוגה מקדימה במובייל',
    'builder.desktopPreview': 'תצוגה מקדימה בדסקטופ',
    'builder.questionnaireLanguage': 'שפת השאלון',
    'builder.questionnaireLanguageDesc': 'שפה לשאלות ותשובות',
    'builder.branding': 'מיתוג ועיצוב',
    'builder.automation': 'הגדרות אוטומציה',
    'builder.readyToSend': 'מוכן לשליחה!',
    'builder.share': 'שתף שאלון',
    'builder.aiSuggestAnswer': 'הצע תשובה באמצעות AI',
    'builder.addQuickQuestion': 'הוסף שאלה מהירה',
    'builder.duplicateQuestionnaire': 'שכפל שאלון',
    'builder.saveAsDraft': 'שמור כטיוטה',
    'builder.autosave': 'שמירה אוטומטית',
    'builder.autosaveEnabled': 'שמירה אוטומטית מופעלת',
    'builder.lastSaved': 'נשמר לאחרונה',
    'builder.unsavedChanges': 'שינויים לא שמורים',
    'builder.dragToReorder': 'גרור לשינוי סדר השאלות',
    'builder.questionOrder': 'סדר השאלות',
    'builder.editInPreview': 'ערוך בתצוגה מקדימה',
    'builder.shareOptions': 'אפשרויות שיתוף',
    'builder.getLink': 'קבל קישור',
    'builder.shareWhatsApp': 'שתף בווטסאפ',
    'builder.shareEmail': 'שתף במייל',
    'builder.shareSMS': 'שלח באמצעות SMS',
    'builder.previewMessage': 'הודעת תצוגה מקדימה',
    'builder.recipientView': 'הנמען יראה',
    'builder.brandingDefaults': 'שמור כמיתוג ברירת מחדל',
    'builder.useDefaults': 'השתמש במיתוג ברירת מחדל',
    'builder.questionSettings': 'הגדרות שאלה',
    'builder.answerType': 'סוג תשובה',
    'builder.validation': 'ולידציה',
    'builder.logic': 'לוגיקת שאלה',
    'builder.skipLogic': 'לוגיקת דילוג',
    'builder.conditionalLogic': 'לוגיקה מותנית',
    'builder.requiredField': 'שדה חובה',
    'builder.optionalField': 'שדה רשות',
    'builder.helpText': 'טקסט עזרה',
    'builder.placeholder': 'טקסט ממלא מקום',
    'builder.characterLimit': 'מגבלת תווים',
    'builder.minLength': 'אורך מינימלי',
    'builder.maxLength': 'אורך מקסימלי',
    'builder.emailValidation': 'ולידציית אימייל',
    'builder.phoneValidation': 'ולידציית טלפון',
    'builder.urlValidation': 'ולידציית URL',
    'builder.numberValidation': 'ולידציית מספר',
    'builder.dateValidation': 'ולידציית תאריך',

    // Responses Hebrew
    'responses.filterResponses': 'סינון תגובות',
    'responses.recent': 'תגובות אחרונות',
    'responses.recentDesc': 'לחץ על כל תגובה כדי להציג פרטים ולהגיב',
    'responses.filterByStatus': 'סינון לפי סטטוס',
    'responses.allResponses': 'כל התגובות',
    'responses.noResponses': 'אין תגובות עדיין',
    'responses.noResponsesDesc': 'ברגע שאנשים יתחילו למלא את השאלונים שלך, התגובות שלהם יופיעו כאן.',
    'responses.shareQuestionnaires': 'שתף את השאלונים שלך',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('he');
  
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'he' ? 'rtl' : 'ltr'} className={language === 'he' ? 'font-hebrew' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};